import turtle

ablak = turtle.Screen()
ablak.setup(600,600)
ablak.bgcolor('white')
ablak.title("Coordinates")
fred = turtle.Turtle()
fred.pencolor("black")
fred.speed(0)
#tengelyek - beosztás
for x in range (12):
    fred.lt(90)
    fred.fd(20)
    fred.rt(90)
    fred.fd(5)
    fred.bk(5)
fred.penup()
fred.goto(0,0)
for x in range(12):
    fred.pendown()
    fred.fd(20)
    fred.lt(90)
    fred.fd(5)
    fred.bk(5)
    fred.rt(90)
fred.penup()
fred.goto(0,0)
for x in range(12):
    fred.pendown()
    fred.bk(20)
    fred.lt(90)
    fred.fd(5)
    fred.bk(5)
    fred.rt(90)
fred.penup()
fred.goto(0, 0)
for x in range (12):
    fred.pendown()
    fred.rt(90)
    fred.fd(20)
    fred.lt(90)
    fred.fd(5)
    fred.bk(5)
fred.penup()
fred.goto(250,0)
fred.write("x")
fred.goto(0,250)
fred.write("y")
fred.goto(0,0)
ablak.exitonclick()